@echo off
echo Starting Indian Bangali Riders Backend...
start cmd /k "cd backend && npm run dev"
echo Starting Indian Bangali Riders Frontend...
start cmd /k "cd frontend && npm run dev"
echo Launching Browser...
timeout /t 5
start http://localhost:5173
